# Generated by Django 5.0.3 on 2024-04-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_bar_app', '0002_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lessons',
        ),
    ]
