# Generated by Django 5.0.3 on 2024-04-14 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_bar_app', '0004_remove_lesson_completed_userlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTextbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress_bar_app.textbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress_bar_app.customuser')),
            ],
        ),
    ]
