# Generated by Django 5.0.3 on 2024-04-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_bar_app', '0005_usertextbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='someslug', max_length=255),
            preserve_default=False,
        ),
    ]
